/*
 * 👋 Hey there!
 * This file is auto-generated by @graphql-codegen.
 * Don't edit it manually or your changes will be lost.
 */

import * as Types from '../../../graphql/types';

import { gql } from '@apollo/client';
import * as Apollo from '@apollo/client';
const defaultOptions = {} as const;
export type ToggleTaskCompletionMutationVariables = Types.Exact<{
  input: Types.TaskUpdateInput;
}>;


export type ToggleTaskCompletionMutation = { __typename?: 'Mutation', taskUpdate?: { __typename?: 'Task', id: number, complete: boolean } | null | undefined };


export const ToggleTaskCompletionDocument = gql`
    mutation ToggleTaskCompletion($input: TaskUpdateInput!) {
  taskUpdate(input: $input) {
    id
    complete
  }
}
    `;
export type ToggleTaskCompletionMutationFn = Apollo.MutationFunction<ToggleTaskCompletionMutation, ToggleTaskCompletionMutationVariables>;

/**
 * __useToggleTaskCompletionMutation__
 *
 * To run a mutation, you first call `useToggleTaskCompletionMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useToggleTaskCompletionMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [toggleTaskCompletionMutation, { data, loading, error }] = useToggleTaskCompletionMutation({
 *   variables: {
 *      input: // value for 'input'
 *   },
 * });
 */
export function useToggleTaskCompletionMutation(baseOptions?: Apollo.MutationHookOptions<ToggleTaskCompletionMutation, ToggleTaskCompletionMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<ToggleTaskCompletionMutation, ToggleTaskCompletionMutationVariables>(ToggleTaskCompletionDocument, options);
      }
export type ToggleTaskCompletionMutationHookResult = ReturnType<typeof useToggleTaskCompletionMutation>;
export type ToggleTaskCompletionMutationResult = Apollo.MutationResult<ToggleTaskCompletionMutation>;
export type ToggleTaskCompletionMutationOptions = Apollo.BaseMutationOptions<ToggleTaskCompletionMutation, ToggleTaskCompletionMutationVariables>;